### ISSUE TITLE
Molt stops running with `TypeError: scheme 'node' not supported`

### ISSUE THREAD

**Issue by 5ouma** [hasundue/molt#234]
When I run `molt deno.json -w` with the [`deno.json`](https://github.com/5ouma/reproxy/blob/6687934ab08a2774525b560752360b8ae6bca386/deno.json) and [`deno.lock`](https://github.com/5ouma/reproxy/blob/6687934ab08a2774525b560752360b8ae6bca386/deno.lock), Molt stops with this error.
I was also observed with Molt Action. (log is [here](https://github.com/5ouma/reproxy/actions/runs/10551726698/job/29229556764))

```
error: Uncaught (in promise) TypeError: scheme 'node' not supported
      const res = await fetch(specifier);
                        ^
    at mainFetch (ext:deno_fetch/26_fetch.js:152:43)
    at ext:deno_fetch/26_fetch.js:353:9
    at new Promise (<anonymous>)
    at fetch (ext:deno_fetch/26_fetch.js:316:18)
    at https://jsr.io/@molt/core/0.19.8/locks.ts:69:25
    at Array.map (<anonymous>)
    at https://jsr.io/@molt/core/0.19.8/locks.ts:68:37
    at eventLoopTick (ext:core/01_core.js:174:7)
    at async Promise.all (index 0)
    at async createRemoteLock (https://jsr.io/@molt/core/0.19.8/locks.ts:65:3)
```

Even if it stops with the error, both files are changed correctly.

**Comment by hasundue** [comment]
Sorry for late but thank you for reporting.
Sounds a serious one but probably easy to fix with the provided information.
I'm still busy in finalization of moving so it might take some time to be done.
